redis:
  image: jambr/sn.redis 
  restart: always

rabbitmq:
  image: jambr/sn.rabbitmq 
  restart: always
  ports:
    - "15672:15672"

picker: 
  image: jambr/sn.picker
  restart: always
  ports:
    - "8001:8001"
  links:
    - redis
    - rabbitmq

crawl-news: 
  image: jambr/sn.crawl.news
  restart: always
  links:
    - redis
    - rabbitmq

crawl-market: 
  image: jambr/sn.crawl.market
  restart: always
  links:
    - redis
    - rabbitmq
